import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function CourseLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>
            <h1 className="font-main text-center text-2xl font-medium mt-4">Course</h1>
            <div>{children}</div> 
        </body>
    </html>
  )
}

